# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'
  
variables:
  scheme: 'SeeEyePeeDee'
  sdk: 'iphoneos'
  configuration: 'Debug'
steps:
- task: Xcode@5
  displayName: 'Running XC Test'
  inputs:
    actions: 'test'
    sdk: 'iphoneos'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
    signingOption: 'auto'
    publishJUnitResults: 'build/reports/junit.xml'
- task: Xcode@5
  displayName: 'Build app'
  inputs:
    sdk: '$(sdk)'
    scheme: '$(scheme)'
    configuration: '$(configuration)'
    xcodeVersion: 'default'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
