# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'
  
variables:
  - group: ios-pipeline
  - name: scheme
    value: 'SeeEyePeeDee'
  - name: sdk
    value: 'iphoneos'
  - name: configuration
    value: 'Release'

steps:
- task: Xcode@5
  inputs:
    sdk: '$(ios-pipeline.sdk)'
    scheme: '$(ios-pipeline.scheme)'
    configuration: '$(ios-pipeline.configuration)'
    xcodeVersion: 'default'
    exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
    packageApp: false
